apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-dev
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: charts/prometheus
    repoURL: "https://github.com/effip24/argotest.git"
    targetRevision: main
    helm:
      releaseName: prometheus
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
