apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app-prod
spec:
  destination:
    namespace: apps
    server: "https://kubernetes.default.svc"
  source:
    path: argocd/apps/prod
    repoURL: "https://github.com/effip24/argotest.git"
    targetRevision: main
  project: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
